steps:
  - label: ":elasticsearch: Serverless :rspec: Unit Tests :ruby: v{{ matrix.ruby }}"
    agents:
      provider: "gcp"
    env:
      RUBY_VERSION: "{{ matrix.ruby }}"
      TEST_SUITE: 'unit'
    matrix:
      setup:
        ruby:
          - "3.2"
          - "3.1"
          - "3.0"
    command: './.buildkite/run-tests.sh'
  - label: ":elasticsearch: Serverless :rspec: API Tests :ruby: v{{ matrix.ruby }}"
    agents:
      provider: "gcp"
    env:
      RUBY_VERSION: "{{ matrix.ruby }}"
      TEST_SUITE: 'api'
    matrix:
      setup:
        ruby:
          - "3.2"
          - "3.1"
          - "3.0"
    command: './.buildkite/run-tests.sh'
