steps:
  - key: tests
    label: ":elasticsearch: Serverless :rspec: API Tests :ruby: {{ matrix.ruby_source}}:{{ matrix.ruby }}"
    agents:
      provider: "gcp"
    env:
      RUBY_VERSION: "{{ matrix.ruby }}"
      TEST_SUITE: 'api'
      RUBY_SOURCE: "{{ matrix.ruby_source }}"
      EC_PROJECT_PREFIX: 'sl_ruby'
      CLOUD_CREDENTIALS_PATH: 'secret/ci/elastic-elasticsearch-serverless-ruby/cloud-access'
    matrix:
      setup:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
        ruby_source:
          - 'ruby'
      adjustments:
        - with:
            ruby_source: 'jruby'
            ruby: '9.4'
    command: './.buildkite/run-tests.sh'
