name: main
on: [push]

jobs:
  rspec:
    strategy:
      matrix:
        ruby: [ '3.2', 'jruby-9.4' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run unit tests
      run: bundle exec rake spec:unit
    - name: Run stack compatiblity tests
      run: bundle exec rake spec:stack
